
# application.properties

spring.application.name=MySpringBoot4Project

# MariaDB
spring.datasource.url=jdbc:mariadb://172.17.128.1:3306/lab_db
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=lab
spring.datasource.password=lab


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

