myboot.name=Spring \uC6B4\uC601\uD658\uACBD

# log level - info
logging.level.com.rookies6.myspringboot4project=info

# MariaDB config
spring.datasource.url=jdbc:mariadb://172.17.128.1:3306/lab_db
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=lab
spring.datasource.password=lab

${DB_DATABASE:lab_db}
spring.datasource.username=${DB_USERNAME:lab}
spring.datasource.password=${DB_PASSWORD:lab}
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# 1:N \uC5F0\uAD00\uAD00\uACC4\uC5D0\uC11C\uC758 N+1 Problem \uD574\uACB0\uD558\uAE30 \uC704\uD55C \uC124\uC815 in( ?,?,? ... )
spring.jpa.properties.hibernate.default_batch_fetch_size=100