spring.application.name=MySpringBoot4Project
spring.profiles.active=test

# 기본 myprop 설정
myprop.username=springboot
myprop.port=${random.int(1,100)}

# myboot 설정
myboot.name=Spring 기본환경
myboot.age=${random.int(1,100)}
myboot.fullName=${myboot.name} Boot

# H2 In-Memory DB 설정
spring.datasource.url=jdbc:h2:mem:d-b-1;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console & Actuator
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always